# -*- coding: utf-8 -*-
"""Grover's 00 EC.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13RM5RKGT-YvHlVl0jq8dk9gop67uFrrY
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install qiskit qiskit-ibm-runtime
# %pip install 'qiskit[visualization]'
# %pip install qiskit-aer

from qiskit import QuantumRegister, ClassicalRegister, QuantumCircuit
import math
from qiskit.visualization import plot_distribution, plot_histogram
from qiskit_ibm_runtime import QiskitRuntimeService
from qiskit.transpiler.preset_passmanagers import generate_preset_pass_manager
from qiskit_ibm_runtime import SamplerV2 as Sampler
from qiskit_aer import AerSimulator
from qiskit_aer.noise import (
    NoiseModel,
    QuantumError,
    ReadoutError,
    depolarizing_error,
    pauli_error,
    thermal_relaxation_error,
)

pi = math.pi
q = QuantumRegister(18,'q')
c = ClassicalRegister(2,'c')
qc = QuantumCircuit(q,c)

QiskitRuntimeService.save_account(channel="ibm_quantum", token="Your Token Here", overwrite=True, set_as_default=True)
service = QiskitRuntimeService(channel='ibm_quantum')
backend = service.least_busy(min_num_qubits=127)

target = backend.target
pm = generate_preset_pass_manager(target=target, optimization_level=3)
circuit_qc = pm.run(qc)
noise_model = NoiseModel.from_backend(backend)

"""Encoding"""

qc.cx(q[0], q[6])
qc.cx(q[1], q[7])
qc.cx(q[0], q[12])
qc.cx(q[1], q[13])
qc.h(q[0])
qc.h(q[1])
qc.h(q[6])
qc.h(q[7])
qc.h(q[12])
qc.h(q[13])
qc.cx(q[0], q[2])
qc.cx(q[1], q[3])
qc.cx(q[0], q[4])
qc.cx(q[1], q[5])
qc.cx(q[6], q[8])
qc.cx(q[7], q[9])
qc.cx(q[6], q[10])
qc.cx(q[7], q[11])
qc.cx(q[12], q[14])
qc.cx(q[13], q[15])
qc.cx(q[12], q[16])
qc.cx(q[13], q[17])

qc.barrier()

"""Grover's Algorithm"""

qc.h(range(18))

qc.h(q[0])
qc.h(q[1])
qc.x(q[0])
qc.x(q[1])
qc.cz(q[0],q[1])
qc.x(q[0])
qc.x(q[1])
qc.h(q[0])
qc.h(q[1])
qc.x(q[0])
qc.x(q[1])
qc.h(q[1])
qc.cx(q[0],q[1])
qc.h(q[1])
qc.x(q[0])
qc.x(q[1])
qc.h(q[0])
qc.h(q[1])

qc.h(q[2])
qc.h(q[3])
qc.x(q[2])
qc.x(q[3])
qc.cz(q[2],q[3])
qc.x(q[2])
qc.x(q[3])
qc.h(q[2])
qc.h(q[3])
qc.x(q[2])
qc.x(q[3])
qc.h(q[3])
qc.cx(q[2],q[3])
qc.h(q[3])
qc.x(q[2])
qc.x(q[3])
qc.h(q[2])
qc.h(q[3])

qc.h(q[4])
qc.h(q[5])
qc.x(q[4])
qc.x(q[5])
qc.cz(q[4],q[5])
qc.x(q[4])
qc.x(q[5])
qc.h(q[4])
qc.h(q[5])
qc.x(q[4])
qc.x(q[5])
qc.h(q[5])
qc.cx(q[4],q[5])
qc.h(q[5])
qc.x(q[4])
qc.x(q[5])
qc.h(q[4])
qc.h(q[5])

qc.h(q[6])
qc.h(q[7])
qc.x(q[6])
qc.x(q[7])
qc.cz(q[6],q[7])
qc.x(q[6])
qc.x(q[7])
qc.h(q[6])
qc.h(q[7])
qc.x(q[6])
qc.x(q[7])
qc.h(q[7])
qc.cx(q[6],q[7])
qc.h(q[7])
qc.x(q[6])
qc.x(q[7])
qc.h(q[6])
qc.h(q[7])

qc.h(q[8])
qc.h(q[9])
qc.x(q[8])
qc.x(q[9])
qc.cz(q[8],q[9])
qc.x(q[8])
qc.x(q[9])
qc.h(q[8])
qc.h(q[9])
qc.x(q[8])
qc.x(q[9])
qc.h(q[9])
qc.cx(q[8],q[9])
qc.h(q[9])
qc.x(q[8])
qc.x(q[9])
qc.h(q[8])
qc.h(q[9])

qc.h(q[10])
qc.h(q[11])
qc.x(q[10])
qc.x(q[11])
qc.cz(q[10],q[11])
qc.x(q[10])
qc.x(q[11])
qc.h(q[10])
qc.h(q[11])
qc.x(q[10])
qc.x(q[11])
qc.h(q[11])
qc.cx(q[10],q[11])
qc.h(q[11])
qc.x(q[10])
qc.x(q[11])
qc.h(q[10])
qc.h(q[11])

qc.h(q[12])
qc.h(q[13])
qc.x(q[12])
qc.x(q[13])
qc.cz(q[12],q[13])
qc.x(q[12])
qc.x(q[13])
qc.h(q[12])
qc.h(q[13])
qc.x(q[12])
qc.x(q[13])
qc.h(q[13])
qc.cx(q[12],q[13])
qc.h(q[13])
qc.x(q[12])
qc.x(q[13])
qc.h(q[12])
qc.h(q[13])

qc.h(q[14])
qc.h(q[15])
qc.x(q[14])
qc.x(q[15])
qc.cz(q[14],q[15])
qc.x(q[14])
qc.x(q[15])
qc.h(q[14])
qc.h(q[15])
qc.x(q[14])
qc.x(q[15])
qc.h(q[15])
qc.cx(q[14],q[15])
qc.h(q[15])
qc.x(q[14])
qc.x(q[15])
qc.h(q[14])
qc.h(q[15])

qc.h(q[16])
qc.h(q[17])
qc.x(q[16])
qc.x(q[17])
qc.cz(q[16],q[17])
qc.x(q[16])
qc.x(q[17])
qc.h(q[16])
qc.h(q[17])
qc.x(q[16])
qc.x(q[17])
qc.h(q[17])
qc.cx(q[16],q[17])
qc.h(q[17])
qc.x(q[16])
qc.x(q[17])
qc.h(q[16])
qc.h(q[17])

qc.h(range(18))

qc.barrier()

"""Decoding"""

qc.cx(q[0], q[2])
qc.cx(q[1], q[3])
qc.cx(q[0], q[4])
qc.cx(q[1], q[5])
qc.ccx(q[4], q[2], q[0])
qc.ccx(q[5], q[3], q[1])
qc.cx(q[6], q[8])
qc.cx(q[7], q[9])
qc.cx(q[6], q[10])
qc.cx(q[7], q[11])
qc.ccx(q[10], q[8], q[6])
qc.ccx(q[11], q[9], q[7])
qc.cx(q[12], q[14])
qc.cx(q[13], q[15])
qc.cx(q[12], q[16])
qc.cx(q[13], q[17])
qc.ccx(q[16], q[14], q[12])
qc.ccx(q[17], q[15], q[13])
qc.h(q[0])
qc.h(q[1])
qc.h(q[6])
qc.h(q[7])
qc.h(q[12])
qc.h(q[13])
qc.cx(q[0], q[6])
qc.cx(q[1], q[7])
qc.cx(q[0], q[12])
qc.cx(q[1], q[13])
qc.ccx(q[12], q[6], q[0])
qc.ccx(q[13], q[7], q[1])

qc.barrier()

"""Measure the logical qubits"""

qc.measure(q[0], 0)
qc.measure(q[1], 1)


"""Run on IBM Quantum Machine"""

sampler = Sampler(mode=backend)
sampler.options.default_shots = 1_024
job = sampler.run([circuit_qc])
results = job.result()

"""Run Simulator"""

#Noisy
simulator = AerSimulator(noise_model=noise_model)
result = simulator.run(qc).result()

#Noiseless
simulator = AerSimulator()
result = simulator.run(qc).result()
