# -*- coding: utf-8 -*-
"""Grover's 101.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MLW94RhPxWqorPvaSmhtD85XNqtJ0y1F
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install qiskit qiskit-ibm-runtime
# %pip install qiskit-aer
# %pip install 'qiskit[visualization]'

from qiskit import QuantumRegister, ClassicalRegister, QuantumCircuit, transpile
import math
from qiskit.visualization import plot_distribution, plot_histogram
from qiskit_ibm_runtime import QiskitRuntimeService
from qiskit.transpiler.preset_passmanagers import generate_preset_pass_manager
from qiskit_ibm_runtime import SamplerV2 as Sampler
from qiskit_aer import AerSimulator
from qiskit_aer.noise import (
    NoiseModel,
    QuantumError,
    ReadoutError,
    depolarizing_error,
    pauli_error,
    thermal_relaxation_error,
)

pi = math.pi
q = QuantumRegister(3,'q')
c = ClassicalRegister(3,'c')
qc = QuantumCircuit(q,c)

QiskitRuntimeService.save_account(channel="ibm_quantum", token="Your Token Here", overwrite=True, set_as_default=True)
service = QiskitRuntimeService(channel='ibm_quantum')
backend = service.least_busy(min_num_qubits=127)

target = backend.target
pm = generate_preset_pass_manager(target=target, optimization_level=3)
circuit_qc = pm.run(qc)
noise_model = NoiseModel.from_backend(backend)

"""Grover's"""

qc.h(range(3))
qc.x(q[1])
qc.ccz(q[0], q[1], q[2])
qc.x(q[1])
qc.h(range(3))
qc.x(range(3))
qc.h(q[2])
qc.ccx(q[0], q[1], q[2])
qc.x(q[0])
qc.x(q[1])
qc.h(q[2])
qc.h(q[0])
qc.h(q[1])
qc.x(q[2])
qc.h(q[2])
qc.measure_all()

qc.draw('mpl', fold=False, idle_wires=False)

"""Run Simulation"""

simulator = AerSimulator(noise_model=noise_model)
result = simulator.run(qc).result()

counts = result.get_counts(qc)
plot_histogram(counts)

simulator = AerSimulator()
result = simulator.run(qc).result()

counts = result.get_counts(qc)
plot_histogram(counts)

"""Run on IBM Quantum Computer"""

sampler = Sampler(mode=backend)
sampler.options.default_shots = 1_024
result = sampler.run([circuit_qc]).result()

dist = result[0].data.c.get_counts()
plot_histogram(dist)